import { LightningElement, api, track } from 'lwc';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';
import getOAuthInfo from '@salesforce/apex/CollaborationSetupController.getOAuthInfo';
import provisionProvider from '@salesforce/apex/CollaborationSetupController.provisionProvider';
import populateProviderCredentials from '@salesforce/apex/CollaborationSetupController.populateProviderCredentials';
import verifyConnection from '@salesforce/apex/CollaborationSetupController.verifyConnection';
import getDestinations from '@salesforce/apex/CollaborationSetupController.getDestinations';
import sendTestMessage from '@salesforce/apex/CollaborationSetupController.sendTestMessage';
import disconnectProvider from '@salesforce/apex/CollaborationSetupController.disconnect';
import getAuthenticationUrl from '@salesforce/apex/CollaborationSetupController.getAuthenticationUrl';
import saveProviderConfiguration from '@salesforce/apex/CollaborationSetupController.saveProviderConfiguration';
import getProviderState from '@salesforce/apex/CollaborationSetupController.getProviderState';
import saveProviderState from '@salesforce/apex/CollaborationSetupController.saveProviderState';

const CONFIGURED_MASK = '••••••••••••';

export default class CollaborationNotifications extends LightningElement {
    @api provider;
    @api slackEnabled = false;
    @api microsoftEnabled = false;
    @track slack = this.emptyProvider();
    @track microsoft = this.emptyProvider();
    slackClientId = ''; slackSecret = ''; tenantId = ''; microsoftClientId = ''; microsoftSecret = '';
    slackInstructionPhase = 1;
    microsoftInstructionPhase = 1;

    async connectedCallback() { if (this.showSlack) await this.initializeProvider('slack'); if (this.showMicrosoft) await this.initializeProvider('microsoft'); }
    disconnectedCallback() { if (this._authPollTimer) clearTimeout(this._authPollTimer); if (this._focusHandler) window.removeEventListener('focus', this._focusHandler); }
    privateSlackChannels = false;
    emptyProvider() { return { callbackUrl: '', authUrl: '', configured: false, secureConfigured: false, connected: false, identity: '', identityId: '', accountName: '', options: [], teamOptions: [], channelId: '', teamId: '', busy: false, operation: '', testSucceeded: false, error: '', authInitiated: false }; }
    get slackStatus() { return this.slack.connected ? `Connected: ${this.slack.identity}` : this.slack.operation === 'saving' ? 'Saving Configuration' : this.slack.operation === 'connecting' ? 'Authorization in Progress' : this.slack.error ? this.slack.authInitiated ? 'Connection Error' : 'Configuration Error' : this.slack.secureConfigured && this.slack.configured ? 'Ready to Authorize' : 'Not Configured'; }
    get microsoftStatus() { return this.microsoft.connected ? `Connected: ${this.microsoft.identity}` : this.microsoft.operation === 'saving' ? 'Saving Configuration' : this.microsoft.operation === 'connecting' ? 'Authorization in Progress' : this.microsoft.error ? this.microsoft.authInitiated ? 'Connection Error' : 'Configuration Error' : this.microsoft.secureConfigured && this.microsoft.configured ? 'Ready to Authorize' : 'Not Configured'; }
    get slackCanTest() { return !this.slack.connected || !this.slack.channelId || this.slack.busy; }
    get microsoftCanTest() { return !this.microsoft.connected || !this.microsoft.teamId || !this.microsoft.channelId || this.microsoft.busy; }
    get slackConnectDisabled() { return !this.slackEnabled || !this.slack.secureConfigured || !this.slack.configured || this.slack.busy; }
    get microsoftConnectDisabled() { return !this.microsoftEnabled || !this.microsoft.secureConfigured || !this.microsoft.configured || this.microsoft.busy; }
    get slackCredentialsUnchanged() { return this.slackClientId === CONFIGURED_MASK && this.slackSecret === CONFIGURED_MASK; }
    get microsoftCredentialsUnchanged() { return this.microsoftClientId === CONFIGURED_MASK && this.microsoftSecret === CONFIGURED_MASK; }
    get slackSaveDisabled() { return !this.slackEnabled || !this.slack.callbackUrl || this.slackCredentialsUnchanged || !this.validSlackClientId || !this.slackSecret || this.slackSecret === CONFIGURED_MASK || this.slack.busy; }
    get microsoftSaveDisabled() { return !this.microsoftEnabled || !this.microsoft.callbackUrl || this.microsoftCredentialsUnchanged || !this.validTenantId || !this.validMicrosoftClientId || !this.microsoftSecret || this.microsoftSecret === CONFIGURED_MASK || this.microsoft.busy; }
    get slackCheckDisabled() { return !this.slack.secureConfigured || (!this.slack.authInitiated && !this.slack.connected) || this.slack.busy; }
    get microsoftCheckDisabled() { return !this.microsoft.secureConfigured || (!this.microsoft.authInitiated && !this.microsoft.connected) || this.microsoft.busy; }
    get validSlackClientId() { return /^\d+\.\d+$/.test(this.slackClientId.trim()); }
    get validTenantId() { return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(this.tenantId.trim()); }
    get validMicrosoftClientId() { return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(this.microsoftClientId.trim()); }
    get showSlack() { return !this.provider || this.provider === 'slack'; }
    get showMicrosoft() { return !this.provider || this.provider === 'microsoft'; }
    get slackProgress() { return this.slack.testSucceeded ? 'Setup complete — test delivered' : this.slack.connected ? 'Connected — select and test a channel' : this.slack.operation === 'saving' ? 'Saving Configuration' : this.slack.operation === 'connecting' ? 'Authorization in Progress' : this.slack.error ? this.slack.authInitiated ? 'Connection Error' : 'Configuration Error' : this.slack.secureConfigured && this.slack.configured ? 'Ready to Authorize' : 'Configuration required'; }
    get microsoftProgress() { return this.microsoft.testSucceeded ? 'Setup complete — test delivered' : this.microsoft.connected ? 'Connected — select and test a destination' : this.microsoft.operation === 'saving' ? 'Saving Configuration' : this.microsoft.operation === 'connecting' ? 'Authorization in Progress' : this.microsoft.error ? this.microsoft.authInitiated ? 'Connection Error' : 'Configuration Error' : this.microsoft.secureConfigured && this.microsoft.configured ? 'Ready to Authorize' : 'Configuration required'; }
    get slackPhase() { return this.slackInstructionPhase; }
    get microsoftPhase() { return this.microsoftInstructionPhase; }
    get slackPhase1() { return this.slackPhase === 1; } get slackPhase2() { return this.slackPhase === 2; } get slackPhase3() { return this.slackPhase === 3; } get slackPhase4() { return this.slackPhase === 4; }
    get microsoftPhase1() { return this.microsoftPhase === 1; } get microsoftPhase2() { return this.microsoftPhase === 2; } get microsoftPhase3() { return this.microsoftPhase === 3; } get microsoftPhase4() { return this.microsoftPhase === 4; }
    get slackPhase1Class() { return this.phaseClass('slack', 1); } get slackPhase2Class() { return this.phaseClass('slack', 2); } get slackPhase3Class() { return this.phaseClass('slack', 3); } get slackPhase4Class() { return this.phaseClass('slack', 4); }
    get microsoftPhase1Class() { return this.phaseClass('microsoft', 1); } get microsoftPhase2Class() { return this.phaseClass('microsoft', 2); } get microsoftPhase3Class() { return this.phaseClass('microsoft', 3); } get microsoftPhase4Class() { return this.phaseClass('microsoft', 4); }
    get slackPhase1Status() { return this.phaseStatus('slack', 1); } get slackPhase2Status() { return this.phaseStatus('slack', 2); } get slackPhase3Status() { return this.phaseStatus('slack', 3); } get slackPhase4Status() { return this.phaseStatus('slack', 4); }
    get microsoftPhase1Status() { return this.phaseStatus('microsoft', 1); } get microsoftPhase2Status() { return this.phaseStatus('microsoft', 2); } get microsoftPhase3Status() { return this.phaseStatus('microsoft', 3); } get microsoftPhase4Status() { return this.phaseStatus('microsoft', 4); }
    get slackPhase1Disabled() { return this.derivedPhase('slack') < 1; } get slackPhase2Disabled() { return this.derivedPhase('slack') < 2; } get slackPhase3Disabled() { return this.derivedPhase('slack') < 3; } get slackPhase4Disabled() { return this.derivedPhase('slack') < 4; }
    get microsoftPhase1Disabled() { return this.derivedPhase('microsoft') < 1; } get microsoftPhase2Disabled() { return this.derivedPhase('microsoft') < 2; } get microsoftPhase3Disabled() { return this.derivedPhase('microsoft') < 3; } get microsoftPhase4Disabled() { return this.derivedPhase('microsoft') < 4; }
    get slackPhase1Current() { return this.slackPhase === 1 ? 'step' : null; } get slackPhase2Current() { return this.slackPhase === 2 ? 'step' : null; } get slackPhase3Current() { return this.slackPhase === 3 ? 'step' : null; } get slackPhase4Current() { return this.slackPhase === 4 ? 'step' : null; }
    get microsoftPhase1Current() { return this.microsoftPhase === 1 ? 'step' : null; } get microsoftPhase2Current() { return this.microsoftPhase === 2 ? 'step' : null; } get microsoftPhase3Current() { return this.microsoftPhase === 3 ? 'step' : null; } get microsoftPhase4Current() { return this.microsoftPhase === 4 ? 'step' : null; }
    get microsoftChannelDisabled() { return !this.microsoft.teamId || this.microsoft.busy; }
    get slackChannelName() { return this.slack.options.find(x => x.value === this.slack.channelId)?.label || 'the selected channel'; }
    get microsoftTeamName() { return this.microsoft.teamOptions.find(x => x.value === this.microsoft.teamId)?.label || 'the selected Team'; }
    get microsoftChannelName() { return this.microsoft.options.find(x => x.value === this.microsoft.channelId)?.label || 'the selected channel'; }
    derivedPhase(provider) { const state = this[provider]; return state.connected ? 4 : state.secureConfigured && state.configured ? 3 : provider === 'microsoft' ? Math.max(1, this.microsoftInstructionPhase) : Math.max(1, this.slackInstructionPhase); }
    phaseClass(provider, phase) { const selected = provider === 'slack' ? this.slackPhase : this.microsoftPhase; const available = this.derivedPhase(provider); return `phase-button ${phase === selected ? 'current' : phase < available || this[provider].testSucceeded ? 'complete' : 'future'}`; }
    phaseStatus(provider, phase) { const selected = provider === 'slack' ? this.slackPhase : this.microsoftPhase; const available = this.derivedPhase(provider); const state = this[provider]; if (phase === selected) return state.error ? `Error: ${state.error}` : 'Current step'; if (state.testSucceeded || phase < available) return 'Complete'; if (provider === 'slack' && phase >= 3) return 'Save your Slack credentials first.'; if (provider === 'microsoft' && phase === 3) return 'Register the app and configure permissions first.'; return 'Complete the previous step first.'; }
    handlePhaseSelect(e) { const provider = e.currentTarget.dataset.provider; const phase = Number(e.currentTarget.dataset.phase); if (phase > this.derivedPhase(provider)) return; if (provider === 'slack') this.slackInstructionPhase = phase; else this.microsoftInstructionPhase = phase; this.patch(provider, {}); this.focusPhaseHeading(provider); }
    continuePhase(e) { const provider = e.currentTarget.dataset.provider; const next = Number(e.currentTarget.dataset.next); if (provider === 'slack') this.slackInstructionPhase = next; else this.microsoftInstructionPhase = next; this.patch(provider, {}); this.focusPhaseHeading(provider); }
    focusPhaseHeading(provider) { requestAnimationFrame(() => this.template.querySelector(`[data-heading="${provider}"]`)?.focus()); }

    async loadOAuthInfo(provider) { try { const value = await getOAuthInfo({ provider }); this.patch(provider, { callbackUrl: value.callbackUrl || '', authUrl: value.authenticationUrl || '', configured: value.configured, secureConfigured: value.credentialsConfigured === true }); } catch (e) { this.error(e); } }
    async initializeProvider(provider) { try { await provisionProvider({ provider, tenantId: null, privateChannels: false }); const saved = await getProviderState({ provider }); const value = saved.oauthInfo || {}; const restoredComplete = saved.setupComplete === true; if (provider === 'slack') this.privateSlackChannels = saved.privateChannels === true; else this.tenantId = saved.tenantId || ''; if (value.credentialsConfigured === true) { if (provider === 'slack') { this.slackClientId = CONFIGURED_MASK; this.slackSecret = CONFIGURED_MASK; } else { this.microsoftClientId = CONFIGURED_MASK; this.microsoftSecret = CONFIGURED_MASK; } } this.patch(provider, { callbackUrl: value.callbackUrl || '', authUrl: value.authenticationUrl || '', configured: value.configured === true, secureConfigured: value.credentialsConfigured === true, identity: saved.identityName || '', identityId: saved.identityId || '', teamId: saved.teamId || '', channelId: saved.channelId || '', testSucceeded: restoredComplete }); let connected = false; if (value.status === 'Configured' && value.credentialsConfigured === true) connected = await this.verifyProvider(provider, true); const phase = connected ? 4 : value.credentialsConfigured === true ? 3 : 1; if (provider === 'slack') this.slackInstructionPhase = phase; else this.microsoftInstructionPhase = phase; this.patch(provider, {}); if (connected && restoredComplete) this.dispatchEvent(new CustomEvent('setupstatuschange', { detail: { provider, complete: true, identity: this[provider].identity } })); } catch (e) { this.error(e); } }
    patch(provider, value) { this[provider] = { ...this[provider], ...value }; }
    emitToggle(name, value) { this.dispatchEvent(new CustomEvent('providerchange', { detail: { name, value } })); }
    handleSlackToggle(e) { if (!e.target.checked && this.slack.connected && !window.confirm('Disable Slack notifications? The existing connection will be preserved until you explicitly disconnect it.')) { e.target.checked = true; return; } this.slackEnabled = e.target.checked; this.emitToggle('slack', this.slackEnabled); }
    handleMicrosoftToggle(e) { if (!e.target.checked && this.microsoft.connected && !window.confirm('Disable Microsoft Teams notifications? The existing connection will be preserved until you explicitly disconnect it.')) { e.target.checked = true; return; } this.microsoftEnabled = e.target.checked; this.emitToggle('microsoft', this.microsoftEnabled); }
    handlePrivateChannels(e) { this.privateSlackChannels = e.target.checked; }
    handleInput(e) { const input = e.currentTarget; this[input.dataset.field] = input.value; input.setCustomValidity(''); input.reportValidity(); }
    handleCredentialFocus(e) { const input = e.currentTarget; const field = input.dataset.field; if (this[field] === CONFIGURED_MASK) { this[field] = ''; input.value = ''; } }

    async saveSlack() {
        const clientId = this.slackClientId.trim(); const secret = this.slackSecret;
        if (!clientId || !this.validSlackClientId || !secret || !this.slack.callbackUrl || this.slack.busy) { this.showSlackSaveError(!clientId ? 'SLACK_CLIENT_ID_REQUIRED' : !this.validSlackClientId ? 'SLACK_CLIENT_ID_INVALID' : !secret ? 'SLACK_CLIENT_SECRET_REQUIRED' : 'SLACK_CREDENTIAL_CONFIGURATION_FAILED'); return; }
        this.patch('slack', { busy: true, operation: 'saving', error: '', secureConfigured: false });
        try { const value = await saveProviderConfiguration({ provider: 'slack', tenantId: null, privateChannels: this.privateSlackChannels, clientId, clientSecret: secret }); this.slackInstructionPhase = 3; this.slackClientId = CONFIGURED_MASK; this.slackSecret = CONFIGURED_MASK; this.patch('slack', { callbackUrl: value.callbackUrl || this.slack.callbackUrl, authUrl: value.authenticationUrl || '', configured: value.configured === true, secureConfigured: value.credentialsConfigured === true, testSucceeded: false, error: '' }); this.toast('Slack configuration saved'); this.focusPhaseHeading('slack'); }
        catch (e) { const code = this.errorCode(e); this.patch('slack', { configured: false, secureConfigured: false, error: this.messageForCode(code) }); this.showSlackSaveError(code); }
        finally { if (!this.slack.secureConfigured) { this.slackSecret = ''; this.clearSecret('slackSecret'); } this.patch('slack', { busy: false, operation: '' }); }
    }
    async saveMicrosoft() {
        const tenantId = this.tenantId.trim(); const clientId = this.microsoftClientId.trim(); const secret = this.microsoftSecret;
        if (!tenantId || !this.validTenantId || !clientId || !this.validMicrosoftClientId || !secret || !this.microsoft.callbackUrl || this.microsoft.busy) { const code = !tenantId ? 'MICROSOFT_TENANT_ID_REQUIRED' : !this.validTenantId ? 'INVALID_TENANT_ID' : !clientId ? 'MICROSOFT_CLIENT_ID_REQUIRED' : !this.validMicrosoftClientId ? 'MICROSOFT_CLIENT_ID_INVALID' : !secret ? 'MICROSOFT_CLIENT_SECRET_REQUIRED' : 'MICROSOFT_CREDENTIAL_CONFIGURATION_FAILED'; this.showMicrosoftSaveError(code); return; }
        this.patch('microsoft', { busy: true, operation: 'saving', error: '', secureConfigured: false });
        try { const value = await saveProviderConfiguration({ provider: 'microsoft', tenantId, privateChannels: false, clientId, clientSecret: secret }); this.microsoftInstructionPhase = 3; this.microsoftClientId = CONFIGURED_MASK; this.microsoftSecret = CONFIGURED_MASK; this.patch('microsoft', { callbackUrl: value.callbackUrl || this.microsoft.callbackUrl, authUrl: value.authenticationUrl || '', configured: value.configured === true, secureConfigured: value.credentialsConfigured === true, testSucceeded: false, error: '' }); this.toast('Microsoft configuration saved'); this.focusPhaseHeading('microsoft'); }
        catch (e) { const code = this.errorCode(e); this.patch('microsoft', { configured: false, secureConfigured: false, error: this.messageForCode(code) }); this.showMicrosoftSaveError(code); }
        finally { if (!this.microsoft.secureConfigured) { this.microsoftSecret = ''; this.clearSecret('microsoftSecret'); } this.patch('microsoft', { busy: false, operation: '' }); }
    }
    clearSecret(field) { const input = this.template.querySelector(`[data-field="${field}"]`); if (input) input.value = ''; }
    async connect(e) { const provider = e.currentTarget?.dataset?.provider; if (!provider || !this[provider]) { this.error({ message: 'Unable to identify the collaboration provider. Refresh the page and try again.' }); return; } if (this[provider].busy || this._authWindow && !this._authWindow.closed) return; let authWindow; try { authWindow = window.open('/lightning/page/home', '_blank'); } catch (x) { const message = 'Salesforce browser security prevented the authorization tab from opening.'; this.patch(provider, { error: message }); this.error({ message }); return; } if (!authWindow) { const message = 'Popup blocked. Allow popups for Salesforce and try again.'; this.patch(provider, { error: message }); this.error({ message }); return; } this._authWindow = authWindow; this.patch(provider, { busy: true, operation: 'connecting', error: '' }); try { const url = await getAuthenticationUrl({ provider }); if (!url || !/^https:\/\//i.test(url)) throw new Error('CONFIGURATION_REQUIRED'); authWindow.location.assign(url); this.patch(provider, { authInitiated: true }); this.toast('Complete authorisation in the newly opened tab. Return here when finished.'); this._focusHandler = () => this.verifyProvider(provider); window.addEventListener('focus', this._focusHandler, { once: true }); this.startAuthorizationPolling(provider); } catch (x) { try { if (!authWindow.closed) authWindow.close(); } catch (_) { /* cross-origin window may no longer be script-closeable */ } const message = this.messageForCode(this.errorCode(x)); this.patch(provider, { error: message }); this.error({ message }); this._authWindow = null; } finally { this.patch(provider, { busy: false, operation: '' }); } }
    startAuthorizationPolling(provider) { if (this._authPollTimer) clearTimeout(this._authPollTimer); let attempts = 0; const poll = async () => { attempts += 1; const connected = await this.verifyProvider(provider, true); if (connected) { this._authWindow = null; this.toast(`${provider === 'slack' ? 'Slack' : 'Microsoft Teams'} connected. Return to the original setup tab.`); return; } if (attempts < 80 && this._authWindow) this._authPollTimer = setTimeout(poll, 3000); }; this._authPollTimer = setTimeout(poll, 3000); }
    async verifyProvider(provider, silent = false) {
        if (!provider || !this[provider] || this[provider].busy) return false;
        this.patch(provider, { busy: true, operation: 'checking', error: '' });
        try {
            const id = await verifyConnection({ provider });
            const rows = await getDestinations({ provider, teamId: null });
            const topOptions = rows.map(x => ({ label: x.name, value: x.id }));
            if (provider === 'slack') {
                const channelId = topOptions.some(x => x.value === this.slack.channelId) ? this.slack.channelId : '';
                this.patch('slack', { connected: true, identity: id.name || id.accountName, identityId: id.id || '', accountName: id.accountName || '', channelId, options: topOptions });
            } else {
                const teamId = topOptions.some(x => x.value === this.microsoft.teamId) ? this.microsoft.teamId : '';
                let channelOptions = [];
                if (teamId) { const channels = await getDestinations({ provider: 'microsoft', teamId }); channelOptions = channels.map(x => ({ label: x.name, value: x.id })); }
                const channelId = channelOptions.some(x => x.value === this.microsoft.channelId) ? this.microsoft.channelId : '';
                this.patch('microsoft', { connected: true, identity: id.name || id.accountName, identityId: id.id || '', accountName: id.accountName || '', teamId, channelId, teamOptions: topOptions, options: channelOptions });
            }
            const current = this[provider];
            const selectedChannel = current.options.find(x => x.value === current.channelId);
            const selectedTeam = current.teamOptions.find(x => x.value === current.teamId);
            await saveProviderState({ provider, identityId: id.id || '', identityName: id.name || id.accountName || '', teamId: current.teamId || null, teamName: selectedTeam?.label || null, channelId: current.channelId || null, channelName: selectedChannel?.label || null, tested: current.testSucceeded === true });
            try { if (this._authWindow && !this._authWindow.closed) this._authWindow.close(); window.focus(); } catch (_) { /* browser may restrict cross-origin close/focus */ }
            if (provider === 'slack') this.slackInstructionPhase = 4; else this.microsoftInstructionPhase = 4;
            this.patch(provider, {});
            return true;
        } catch (x) {
            const message = this.messageForCode(this.errorCode(x)); this.patch(provider, { connected: false, error: silent ? '' : message }); if (!silent) this.error({ message }); return false;
        } finally { this.patch(provider, { busy: false, operation: '' }); if (!silent) this._authWindow = null; }
    }
    async verify(e) { await this.verifyProvider(e.currentTarget.dataset.provider); }
    async handleSlackChannel(e) { const channelId = e.detail.value; const option = this.slack.options.find(x => x.value === channelId); this.patch('slack', { channelId, testSucceeded: false }); try { await saveProviderState({ provider: 'slack', identityId: this.slack.identityId, identityName: this.slack.identity, teamId: null, teamName: null, channelId, channelName: option?.label || '', tested: false }); } catch (x) { this.error(x); } }
    async handleTeam(e) { const teamId = e.detail.value; const team = this.microsoft.teamOptions.find(x => x.value === teamId); this.patch('microsoft', { teamId, channelId: '', busy: true, testSucceeded: false }); try { const rows = await getDestinations({ provider: 'microsoft', teamId }); this.patch('microsoft', { options: rows.map(x => ({ label: x.name, value: x.id })) }); await saveProviderState({ provider: 'microsoft', identityId: this.microsoft.identityId, identityName: this.microsoft.identity, teamId, teamName: team?.label || '', channelId: '', channelName: '', tested: false }); } catch (x) { this.error(x); } finally { this.patch('microsoft', { busy: false }); } }
    async handleMicrosoftChannel(e) { const channelId = e.detail.value; const channel = this.microsoft.options.find(x => x.value === channelId); const team = this.microsoft.teamOptions.find(x => x.value === this.microsoft.teamId); this.patch('microsoft', { channelId, testSucceeded: false }); try { await saveProviderState({ provider: 'microsoft', identityId: this.microsoft.identityId, identityName: this.microsoft.identity, teamId: this.microsoft.teamId, teamName: team?.label || '', channelId, channelName: channel?.label || '', tested: false }); } catch (x) { this.error(x); } }
    async test(e) { const provider = e.currentTarget.dataset.provider; const value = this[provider]; this.patch(provider, { busy: true, error: '' }); try { await sendTestMessage({ provider, teamId: value.teamId, channelId: value.channelId }); const channel = value.options.find(x => x.value === value.channelId); const team = value.teamOptions.find(x => x.value === value.teamId); await saveProviderState({ provider, identityId: value.identityId, identityName: value.identity, teamId: value.teamId || null, teamName: team?.label || null, channelId: value.channelId, channelName: channel?.label || '', tested: true }); this.patch(provider, { testSucceeded: true }); this.dispatchEvent(new CustomEvent('setupstatuschange', { detail: { provider, complete: true, identity: value.identity } })); this.toast('Test message sent successfully'); } catch (x) { const raw = x?.body?.message || x?.message || 'Test message failed.'; const message = provider === 'slack' && raw.includes('not_in_channel') ? `Org Monitor has not been added to this channel. Invite @Org Monitor to ${this.slackChannelName}, then select Send Test Message again.` : raw; this.patch(provider, { testSucceeded: false, error: message }); this.error({ message }); } finally { this.patch(provider, { busy: false }); } }
    async disconnect(e) { const provider = e.currentTarget.dataset.provider; if (!window.confirm(`Disconnect ${provider === 'slack' ? 'Slack' : 'Microsoft Teams'}?`)) return; try { await disconnectProvider({ provider }); this[provider] = this.emptyProvider(); await this.loadOAuthInfo(provider); this.toast('Disconnected'); } catch (x) { this.error(x); } }
    async copy(e) { const text = this[e.currentTarget.dataset.provider].callbackUrl; try { await navigator.clipboard.writeText(text); this.toast('Callback URL copied'); } catch (_) { this.error({ message: 'Copy failed. Select and copy the URL manually.' }); } }
    errorCode(e) { return e?.body?.message || e?.message || 'SLACK_CREDENTIAL_CONFIGURATION_FAILED'; }
    messageForCode(code) { const messages = { SLACK_CLIENT_ID_REQUIRED: 'Enter the Slack Client ID.', SLACK_CLIENT_ID_INVALID: 'Enter a valid Slack Client ID in numeric.numeric format.', SLACK_CLIENT_SECRET_REQUIRED: 'Enter the Slack Client Secret.', SLACK_CREDENTIAL_CONFIGURATION_FAILED: 'Salesforce could not configure the packaged Slack credentials.', SLACK_CREDENTIAL_API_UNAVAILABLE: 'The Salesforce secure credential API is unavailable. Try again or contact your Salesforce administrator.', MICROSOFT_TENANT_ID_REQUIRED: 'Enter the Microsoft Directory / Tenant ID.', INVALID_TENANT_ID: 'Enter a valid Microsoft Directory / Tenant GUID.', MICROSOFT_CLIENT_ID_REQUIRED: 'Enter the Microsoft Application / Client ID.', MICROSOFT_CLIENT_ID_INVALID: 'Enter a valid Microsoft Application / Client GUID.', MICROSOFT_CLIENT_SECRET_REQUIRED: 'Enter the Microsoft Client Secret Value.', MICROSOFT_CREDENTIAL_CONFIGURATION_FAILED: 'Salesforce could not configure the packaged Microsoft credentials.', MICROSOFT_CREDENTIAL_API_UNAVAILABLE: 'The Salesforce secure credential API is unavailable. Try again or contact your Salesforce administrator.', CONFIGURATION_REQUIRED: 'Save the provider configuration successfully before connecting.', CALLOUTS_DISABLED: 'In Salesforce Setup, open Named Credentials, select the OrgMonitor provider credential, and enable Enabled for Callouts. Then return here and select Check Connection.', PACKAGE_IDENTITY_PROVIDER_MISSING: 'The packaged identity provider is missing. Reinstall or upgrade Org Monitor.', PACKAGE_EXTERNAL_CREDENTIAL_MISSING: 'The packaged external credential is missing. Reinstall or upgrade Org Monitor.', PACKAGE_NAMED_PRINCIPAL_MISSING: 'The packaged named principal is missing. Reinstall or upgrade Org Monitor.', PACKAGE_NAMED_CREDENTIAL_MISSING: 'The packaged Named Credential is missing. Reinstall or upgrade Org Monitor.', PACKAGE_PERMISSION_SET_MISSING: 'The packaged collaboration permission set is missing. Reinstall or upgrade Org Monitor.', PACKAGE_PERMISSION_ASSIGNMENT_REQUIRED: 'Assign the Org Monitor Collaboration Administrator permission set to your user, then try again.' }; return messages[code] || code; }
    showSlackSaveError(code) { const message = this.messageForCode(code); const field = code.includes('CLIENT_ID') ? 'slackClientId' : code.includes('CLIENT_SECRET') ? 'slackSecret' : null; if (field) { const input = this.template.querySelector(`[data-field="${field}"]`); if (input) { input.setCustomValidity(message); input.reportValidity(); } } this.patch('slack', { error: message }); this.error({ message }); }
    showMicrosoftSaveError(code) { const message = this.messageForCode(code); const field = code.includes('TENANT') ? 'tenantId' : code.includes('CLIENT_ID') ? 'microsoftClientId' : code.includes('CLIENT_SECRET') ? 'microsoftSecret' : null; if (field) { const input = this.template.querySelector(`[data-field="${field}"]`); if (input) { input.setCustomValidity(message); input.reportValidity(); } } this.patch('microsoft', { error: message }); this.error({ message }); }
    toast(message) { this.dispatchEvent(new ShowToastEvent({ title: 'Org Monitor', message, variant: 'success' })); }
    error(e) { this.dispatchEvent(new ShowToastEvent({ title: 'Collaboration setup error', message: e?.body?.message || e?.message || 'Unexpected error', variant: 'error', mode: 'sticky' })); }
}